---
# tasks file for deploy
- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ resource }}"
    location: eastus

- name: Create vnet
  azure_rm_virtualnetwork:
    name: "{{ resource }}-vnet"
    resource_group: "{{ resource }}"
    address_prefixes_cidr:
        - "10.0.0.0/24"

- name: Create a subnet
  azure_rm_subnet:
    name: "{{ resource }}-subnet"
    virtual_network_name: "{{ resource }}-vnet"
    resource_group: "{{ resource }}"
    address_prefix_cidr: "10.0.0.0/24"

- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: "{{ resource }}"
    name: "{{ item }}-ip"
  with_items:
     - "{{ vmname }}"

- name: create security group
  azure_rm_securitygroup:
      resource_group: "{{ resource }}"
      name: "{{ resource }}-security"
      purge_rules: yes
      rules:
          - name: 'AllowSSH'
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1000
            direction: Inbound
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
                - 80
                - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range:
                - 5985
                - 5986

- name: Create a network interface using existing security group and public IP
  azure_rm_networkinterface:
        name: "{{ item }}-nic"
        resource_group: "{{ resource }}"
        virtual_network_name: "{{ resource }}-vnet"
        subnet_name: "{{ resource }}-subnet"
        security_group_name: "{{ resource }}-security"
        public_ip_address_name: "{{ item }}-ip"
  with_items:
    - "{{ vmname }}"

- name: create a storage account
  azure_rm_storageaccount:
    resource_group: "{{ resource }}"
    name: "{{ item }}sa"
    type: Standard_LRS
  with_items:
    - "{{ vmname }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource }}"
    name: linux
    vm_size: "{{ vmsize }}"
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    image:
     offer: CentOS
     publisher: OpenLogic
     sku: '7.2'
     version: latest
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource }}"
    name: ubuntu
    vm_size: "{{ vmsize }}"
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    image:
     offer: CentOS
     publisher: OpenLogic
     sku: '7.2'
     version: latest
 - name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource }}"
    name: windows
    vm_size: "{{ vmsize }}"
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    image:
     offer: WindowsServer
     publisher: MicrosoftWindowsServer
     sku: 2019-Datacenter
     version: latest
